last_updated: "2026-03-01"
legitimate_clubs:
  - name: "The American Steamship Owners Mutual Protection and Indemnity Association (American Club)"
    short: "American Club"
  - name: "Assuranceforeningen Gard"
    short: "Gard"
  - name: "The Britannia Steam Ship Insurance Association (Britannia)"
    short: "Britannia"
  - name: "The Japan Ship Owners' Mutual Protection & Indemnity Association (Japan P&I Club)"
    short: "Japan P&I"
  - name: "The London Steam-Ship Owners' Mutual Insurance Association (London Club)"
    short: "London Club"
  - name: "The North of England P&I Association (North)"
    short: "North"
  - name: "The Shipowners' Mutual Protection and Indemnity Association (Luxembourg) (Shipowners')"
    short: "Shipowners'"
  - name: "Skuld"
    short: "Skuld"
  - name: "The Standard Club"
    short: "Standard"
  - name: "The Steamship Mutual Underwriting Association (Bermuda) (Steamship Mutual)"
    short: "Steamship Mutual"
  - name: "Sveriges Angfartygs Assurans Forening (The Swedish Club)"
    short: "Swedish Club"
  - name: "United Kingdom Mutual Steam Ship Assurance Association (Bermuda) (UK Club)"
    short: "UK Club"
  - name: "The West of England Ship Owners Mutual Insurance Association (Luxembourg) (West)"
    short: "West"
known_fraudulent:
  - "Pacific Maritime Insurance"
  - "Global Shipping Guarantee Corp"
